root: true
parser: "@typescript-eslint/parser"
ignorePatterns: dist
parserOptions:
  project: ./tsconfig.json
env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - "@jiralite/eslint-config-neon/common"
  - "@jiralite/eslint-config-neon/module"
  - "@jiralite/eslint-config-neon/node"
  - "@jiralite/eslint-config-neon/typescript"
  - "@jiralite/eslint-config-neon/prettier"
plugins:
  - "@typescript-eslint"
reportUnusedDisableDirectives: true
rules:
  jsdoc/check-param-names: 0
