name: Publish
on:
  release:
    types: [prereleased, released]
permissions:
  id-token: write
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
          run_install: |
            - args: [--frozen-lockfile]

      - name: Publish package
        run: pnpm publish --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  jsr:
    name: JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
          run_install: |
            - args: [--frozen-lockfile]

      - name: Publish package
        run: pnpm dlx jsr publish
