name: Test
on: [pull_request, push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for typographical errors
        uses: crate-ci/typos@master

      - name: Install Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Lint codebase
        run: pnpm run lint
