name: Test
on: [pull_request, push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for typographical errors
        uses: crate-ci/typos@master

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
          run_install: |
            - args: [--frozen-lockfile]

      - name: Lint codebase
        run: pnpm run lint
